spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simplesns
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200306
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop